apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  # This is the name of your Kargo project
  name: poc-project
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: poc-image-registry
  namespace: poc-project
spec:
  subscriptions:
    - image:
        repoURL: ghcr.io/kadamanas93/simple-go-http-server
        imageSelectionStrategy: NewestBuild
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: demo-promo-process
  namespace: poc-project
spec:
  vars:
  - name: gitopsRepo
    value: https://github.com/kadamanas93/simple-go-http-server.git
  - name: imageRepo
    value: ghcr.io/kadamanas93/simple-go-http-server
  steps:
  - config:
      checkout:
      - branch: main
        path: ./src
      - branch: stage/${{ ctx.stage }}
        create: true
        path: ./out
      repoURL: ${{ vars.gitopsRepo }}
    uses: git-clone
  - config:
      path: ./out
    uses: git-clear
  - as: update
    config:
      images:
      - image: ${{ vars.imageRepo }}
        tag: ${{ imageFrom(vars.imageRepo).Tag }}
      path: ./src/k8s/app/base
    uses: kustomize-set-image
  - config:
      outPath: ./out
      path: ./src/k8s/app/stages/${{ ctx.stage }}
    uses: kustomize-build
  - as: commit
    config:
      message: ${{ task.outputs.update.commitMessage }}
      path: ./out
    uses: git-commit
  - config:
      path: ./out
    uses: git-push
  - config:
      apps:
      - name: simple-go-http-server-${{ ctx.stage }}
        sources:
        - desiredRevision: ${{ task.outputs.commit.commit }}
          repoURL: ${{ vars.gitopsRepo }}
    uses: argocd-update
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: poc-project
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: poc-image-registry
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: poc-project
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: poc-image-registry
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: poc-project
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: poc-image-registry
    sources:
      stages:
      - staging
  promotionTemplate:
    spec:
      steps:
      - task:
          name: demo-promo-process
        as: promo-process
