# This file defines the 3 ArgoCD applications (dev, staging, prod)
# that monitor the GitOps repo and deploy to the correct namespace.

apiVersion: v1
kind: Namespace
metadata:
  name: poc-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: poc-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: poc-prod
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: simple-go-http-server
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: dev
      - stage: staging
      - stage: prod
  template:
    metadata:
      name: simple-go-http-server-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: simple-go-http-server:{{stage}}
    spec:
      project: default
      source:
        repoURL: https://github.com/kadamanas93/simple-go-http-server.git
        targetRevision: k8s/app/stages/{{stage}}
        path: .
      destination:
        server: https://kubernetes.default.svc
        namespace: poc-{{stage}}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
