apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base

# Kargo will update this 'newTag' value.
images:
  - name: localhost:5000/simple-go-http-server
    newTag: "0.0.1" # This is the initial tag
